### ISSUE TITLE
mv 命令的实现错误

### ISSUE THREAD

**Issue by youkaichao** [JL-Cheng/xv6-public#5]
复现案例：
制造一个文件a.txt, 里面包含130个字符a，执行 mv a.txt b.txt, 发现b里面就包含了256个字符。

初步分析是因为mv.c中的 63~65行中，
        while((length = read(fp_src,buf,bufSize)) > 0){ 
                write(fp_dst,buf,bufSize);
        }
write时应该用length 而不是bufSize

**Comment by JL-Cheng** [comment]
已修正。
